// Code generated by protoc-gen-go. DO NOT EDIT.
// source: median.proto

package median_grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GenerateRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Min                  int64    `protobuf:"varint,3,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  int64    `protobuf:"varint,4,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateRequest) Reset()         { *m = GenerateRequest{} }
func (m *GenerateRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateRequest) ProtoMessage()    {}
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_median_ebf1baf9ad95c7dd, []int{0}
}
func (m *GenerateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateRequest.Unmarshal(m, b)
}
func (m *GenerateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateRequest.Marshal(b, m, deterministic)
}
func (dst *GenerateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateRequest.Merge(dst, src)
}
func (m *GenerateRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateRequest.Size(m)
}
func (m *GenerateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateRequest proto.InternalMessageInfo

func (m *GenerateRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GenerateRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GenerateRequest) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *GenerateRequest) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

type QueryResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Min                  int64    `protobuf:"varint,3,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  int64    `protobuf:"varint,4,opt,name=Max,proto3" json:"Max,omitempty"`
	Sum                  int64    `protobuf:"varint,5,opt,name=Sum,proto3" json:"Sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_median_ebf1baf9ad95c7dd, []int{1}
}
func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (dst *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(dst, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *QueryResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryResponse) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *QueryResponse) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *QueryResponse) GetSum() int64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

// findK的search
type SeachRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Guess                int64    `protobuf:"varint,2,opt,name=Guess,proto3" json:"Guess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeachRequest) Reset()         { *m = SeachRequest{} }
func (m *SeachRequest) String() string { return proto.CompactTextString(m) }
func (*SeachRequest) ProtoMessage()    {}
func (*SeachRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_median_ebf1baf9ad95c7dd, []int{2}
}
func (m *SeachRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeachRequest.Unmarshal(m, b)
}
func (m *SeachRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeachRequest.Marshal(b, m, deterministic)
}
func (dst *SeachRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeachRequest.Merge(dst, src)
}
func (m *SeachRequest) XXX_Size() int {
	return xxx_messageInfo_SeachRequest.Size(m)
}
func (m *SeachRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SeachRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SeachRequest proto.InternalMessageInfo

func (m *SeachRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SeachRequest) GetGuess() int64 {
	if m != nil {
		return m.Guess
	}
	return 0
}

type SearchResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Smaller              int64    `protobuf:"varint,2,opt,name=Smaller,proto3" json:"Smaller,omitempty"`
	Same                 int64    `protobuf:"varint,3,opt,name=Same,proto3" json:"Same,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_median_ebf1baf9ad95c7dd, []int{3}
}
func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (dst *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(dst, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SearchResponse) GetSmaller() int64 {
	if m != nil {
		return m.Smaller
	}
	return 0
}

func (m *SearchResponse) GetSame() int64 {
	if m != nil {
		return m.Same
	}
	return 0
}

func init() {
	proto.RegisterType((*GenerateRequest)(nil), "median_grpc.generateRequest")
	proto.RegisterType((*QueryResponse)(nil), "median_grpc.QueryResponse")
	proto.RegisterType((*SeachRequest)(nil), "median_grpc.SeachRequest")
	proto.RegisterType((*SearchResponse)(nil), "median_grpc.SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MedianClient is the client API for Median service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MedianClient interface {
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Search(ctx context.Context, in *SeachRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type medianClient struct {
	cc *grpc.ClientConn
}

func NewMedianClient(cc *grpc.ClientConn) MedianClient {
	return &medianClient{cc}
}

func (c *medianClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/median_grpc.Median/Generate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medianClient) Search(ctx context.Context, in *SeachRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/median_grpc.Median/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MedianServer is the server API for Median service.
type MedianServer interface {
	Generate(context.Context, *GenerateRequest) (*QueryResponse, error)
	Search(context.Context, *SeachRequest) (*SearchResponse, error)
}

func RegisterMedianServer(s *grpc.Server, srv MedianServer) {
	s.RegisterService(&_Median_serviceDesc, srv)
}

func _Median_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedianServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/median_grpc.Median/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedianServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Median_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedianServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/median_grpc.Median/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedianServer).Search(ctx, req.(*SeachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Median_serviceDesc = grpc.ServiceDesc{
	ServiceName: "median_grpc.Median",
	HandlerType: (*MedianServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _Median_Generate_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Median_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "median.proto",
}

func init() { proto.RegisterFile("median.proto", fileDescriptor_median_ebf1baf9ad95c7dd) }

var fileDescriptor_median_ebf1baf9ad95c7dd = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x9b, 0x26, 0x0d, 0xe8, 0x28, 0x05, 0x9d, 0x18, 0x4c, 0x60, 0xa8, 0x3c, 0x75, 0xca,
	0x00, 0x3c, 0x01, 0x48, 0x54, 0x1d, 0x8a, 0x44, 0x3c, 0x32, 0x20, 0xd3, 0x9c, 0x4a, 0x45, 0xed,
	0x04, 0x3b, 0x96, 0xca, 0x7b, 0xf0, 0xc0, 0x28, 0x4e, 0x2a, 0x25, 0x95, 0x60, 0x62, 0xbb, 0xff,
	0x3f, 0x9f, 0x7d, 0xff, 0x67, 0x18, 0x2b, 0xca, 0x37, 0x52, 0xa7, 0xa5, 0x29, 0xaa, 0x02, 0x4f,
	0x1a, 0xf5, 0xba, 0x36, 0xe5, 0x8a, 0xbf, 0xc0, 0xd9, 0x9a, 0x34, 0x19, 0x59, 0x51, 0x46, 0x9f,
	0x8e, 0x6c, 0x85, 0x13, 0x18, 0x2e, 0x72, 0x16, 0x4c, 0x83, 0x59, 0x94, 0x0d, 0x17, 0x39, 0x5e,
	0xc0, 0xe8, 0xa1, 0x70, 0xba, 0x62, 0xc3, 0x69, 0x30, 0x0b, 0xb3, 0x46, 0xe0, 0x39, 0x84, 0xcb,
	0x8d, 0x66, 0xa1, 0xf7, 0xea, 0xd2, 0x3b, 0x72, 0xc7, 0xa2, 0xd6, 0x91, 0x3b, 0xfe, 0x01, 0xa7,
	0xcf, 0x8e, 0xcc, 0x57, 0x46, 0xb6, 0x2c, 0xb4, 0xa5, 0xff, 0xbb, 0xba, 0x76, 0x84, 0x53, 0x6c,
	0xd4, 0x38, 0xc2, 0x29, 0x7e, 0x07, 0x63, 0x41, 0x72, 0xf5, 0xfe, 0x47, 0x8c, 0xb9, 0x23, 0x6b,
	0xf7, 0x6f, 0x79, 0xc1, 0x9f, 0x60, 0x22, 0x48, 0x9a, 0x7a, 0xec, 0x97, 0x1d, 0x19, 0x1c, 0x09,
	0x25, 0xb7, 0x5b, 0x32, 0xed, 0xe4, 0x5e, 0x22, 0x42, 0x24, 0xa4, 0xa2, 0x76, 0x51, 0x5f, 0xdf,
	0x7c, 0x07, 0x10, 0x2f, 0x3d, 0x5f, 0x7c, 0x84, 0xe3, 0x79, 0x8b, 0x16, 0xaf, 0xd3, 0x0e, 0xf4,
	0xf4, 0x80, 0x78, 0x92, 0xf4, 0xba, 0x3d, 0x64, 0x7c, 0x80, 0xf7, 0x10, 0x37, 0x2b, 0xe2, 0x65,
	0xef, 0x5c, 0x37, 0x6d, 0x72, 0x75, 0xd8, 0xea, 0x44, 0xe2, 0x83, 0xb7, 0xd8, 0x7f, 0xfd, 0xed,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x11, 0x8f, 0x81, 0x0a, 0x02, 0x00, 0x00,
}
